/**
 * Hybrid Logical Clock (HLC) primitive for distributed synchronization.
 */
export class HLC {
  private lastPhysicalTime: number;
  private logicalCounter: number;
  private readonly nodeId: string;

  constructor(nodeId: string) {
    this.nodeId = nodeId;
    this.lastPhysicalTime = Date.now();
    this.logicalCounter = 0;
  }

  /**
   * Generates a new unique, sortable timestamp for an internal or local event.
   * This is used in a distributed system to ensure that every event gets a globally unique,
   * monotonically increasing timestamp that respects physical time as closely as possible.
   * 
   * @returns {string} The encoded timestamp (e.g., 2026-04-08T12:00:00.000Z-0000-nodeId)
   */
  now(): string {
    const currentPhysical = Date.now();

    if (currentPhysical > this.lastPhysicalTime) {
      // Physical clock marched forward, reset logical clock.
      this.lastPhysicalTime = currentPhysical;
      this.logicalCounter = 0;
    } else {
      // Physical clock hasn't moved, or jumped backwards. 
      // Rely on logical clock to push time forward monotonically.
      this.logicalCounter++;
    }

    return this.encode(this.lastPhysicalTime, this.logicalCounter, this.nodeId);
  }

  /**
   * Updates the local clock state based on an incoming timestamp from another node.
   * This guarantees causality in a distributed system: if event A generated a timestamp,
   * and this node receives event A, any subsequent event generated by this node will have
   * a timestamp strictly > event A's timestamp.
   * 
   * @param remoteTimestamp The string timestamp received from a remote node.
   */
  receive(remoteTimestamp: string): void {
    const decoded = this.decode(remoteTimestamp);
    
    const physical = Date.now();
    const maxPhysical = Math.max(physical, this.lastPhysicalTime, decoded.physicalTime);

    if (maxPhysical === this.lastPhysicalTime && maxPhysical === decoded.physicalTime) {
      this.logicalCounter = Math.max(this.logicalCounter, decoded.logicalCounter) + 1;
    } else if (maxPhysical === this.lastPhysicalTime) {
      this.logicalCounter++;
    } else if (maxPhysical === decoded.physicalTime) {
      this.logicalCounter = decoded.logicalCounter + 1;
    } else {
      this.logicalCounter = 0;
    }

    this.lastPhysicalTime = maxPhysical;
  }

  /**
   * Compares two encoded HLC timestamps lexicographically.
   * Because the encoded format is ISO-CCCC-nodeId, plain string
   * comparison correctly reflects happened-before ordering.
   *
   * @returns < 0 if a < b, 0 if equal, > 0 if a > b.
   */
  static compare(a: string, b: string): number {
    return a.localeCompare(b);
  }

  /**
   * Serializes the HLC state into a lexically sortable string.
   * Essential for distributed databases (like CRDTs or local-first sync) because
   * standard string sorting on the encoded format correctly orders events by happened-before relationships
   * and tie-breaks deterministically using the nodeId.
   * 
   * @param physicalTime The physical timestamp in milliseconds.
   * @param logicalCounter The logical counter.
   * @param nodeId The unique node identifier.
   * @returns The string representation.
   */
  encode(physicalTime: number, logicalCounter: number, nodeId: string): string {
    const isoString = new Date(physicalTime).toISOString();
    const paddedCounter = logicalCounter.toString().padStart(4, '0');
    return `${isoString}-${paddedCounter}-${nodeId}`;
  }

  /**
   * Deserializes a string timestamp back into its clock components.
   * Used to inspect remote timestamps or during the sync protocol when resolving conflicts.
   * 
   * @param timestampString The serialized HLC string.
   * @returns An object containing the physical time, logical counter, and nodeId.
   */
  decode(timestampString: string): { physicalTime: number, logicalCounter: number, nodeId: string } {
    const zIndex = timestampString.indexOf('Z');
    if (zIndex === -1) {
      throw new Error(`Invalid HLC timestamp format: missing 'Z' in ${timestampString}`);
    }

    const isoString = timestampString.substring(0, zIndex + 1);
    const physicalTime = new Date(isoString).getTime();

    // The rest is expected to be `-CCCC-NODEID`
    const remainder = timestampString.substring(zIndex + 2); // skip "Z-"
    const counterStr = remainder.substring(0, 4);
    const logicalCounter = parseInt(counterStr, 10);
    
    const nodeId = remainder.substring(5); // skip "CCCC-"

    return { physicalTime, logicalCounter, nodeId };
  }
}
